family: sd
gddpm:
  model: m_lsun_256
  lsun_cat: bedroom
  imgnet_cat: -1
sd:
  variant: v1
  v2_highres: false
  prompt: a colorful toucan with a large beak
  scale: 100.0
  precision: autocast
lr: 0.05
n_steps: 10000
vox:
  model_type: V_SD
  bbox_len: 1.0
  grid_size:
  - 100
  - 100
  - 100
  step_ratio: 0.5
  density_shift: -1.0
  ray_march_weight_thres: 0.0001
  c: 4
  blend_bg_texture: true
  bg_texture_hw: 4
pose:
  rend_hw: 64
  FoV: 60.0
  R: 1.5
score_thres: 8.0
score_dynamic: true
emptiness_scale: 10
emptiness_weight: 10000
emptiness_step: 0.5
emptiness_multiplier: 20.0
depth_weight: 0
var_red: true
